services:
  - type: web
    name: bitespeed-identity
    env: node
    buildCommand: npm install && npm run build && npm run render:migrate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
